// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from prime.djinni

#include "NativePrimeGeneratorDjinni.hpp"  // my header
#include "Marshal.hpp"

namespace Prime {

NativePrimeGeneratorDjinni::NativePrimeGeneratorDjinni() : ::djinni::JniInterface<::Prime::PrimeGeneratorDjinni, NativePrimeGeneratorDjinni>("com/example/anatoly/djinnigenerated/PrimeGeneratorDjinni$CppProxy") {}

NativePrimeGeneratorDjinni::~NativePrimeGeneratorDjinni() = default;


CJNIEXPORT void JNICALL Java_com_example_anatoly_djinnigenerated_PrimeGeneratorDjinni_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::Prime::PrimeGeneratorDjinni>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_example_anatoly_djinnigenerated_PrimeGeneratorDjinni_00024CppProxy_create(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::Prime::PrimeGeneratorDjinni::create();
        return ::djinni::release(::Prime::NativePrimeGeneratorDjinni::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_example_anatoly_djinnigenerated_PrimeGeneratorDjinni_00024CppProxy_native_1generatePrime(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_amount)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::Prime::PrimeGeneratorDjinni>(nativeRef);
        auto r = ref->generate_prime(::djinni::I32::toCpp(jniEnv, j_amount));
        return ::djinni::release(::djinni::List<::djinni::I32>::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace Prime
