// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from prime.djinni

#pragma once

#include "djinni_support.hpp"
#include "prime_generator_djinni.hpp"

namespace Prime {

class NativePrimeGeneratorDjinni final : ::djinni::JniInterface<::Prime::PrimeGeneratorDjinni, NativePrimeGeneratorDjinni> {
public:
    using CppType = std::shared_ptr<::Prime::PrimeGeneratorDjinni>;
    using CppOptType = std::shared_ptr<::Prime::PrimeGeneratorDjinni>;
    using JniType = jobject;

    using Boxed = NativePrimeGeneratorDjinni;

    ~NativePrimeGeneratorDjinni();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativePrimeGeneratorDjinni>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativePrimeGeneratorDjinni>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativePrimeGeneratorDjinni();
    friend ::djinni::JniClass<NativePrimeGeneratorDjinni>;
    friend ::djinni::JniInterface<::Prime::PrimeGeneratorDjinni, NativePrimeGeneratorDjinni>;

};

}  // namespace Prime
